package xyz.codingmentor.consoleclient.service.switchcase.mainmenu.event;

import java.util.Arrays;
import xyz.codingmentor.consoleclient.Application;
import xyz.codingmentor.consoleclient.api.IHTTPRequest;
import xyz.codingmentor.consoleclient.service.http.HTTPRequest;
import static xyz.codingmentor.consoleclient.service.io.EnumReader.getInvitationStatus;
import xyz.codingmentor.consoleclient.service.property.URLProperty;
import xyz.codingmentor.consoleclient.service.switchcase.AbstractCase;
import xyz.codingmentor.team3.registry.dto.invitation.InvitationDTO;
import xyz.codingmentor.team3.registry.entity.invitation.InvitationStatus;

/**
 *
 * @author brianelete
 */
public class EditInvitationCase extends AbstractCase {

    private final IHTTPRequest<InvitationDTO> httpRequest;
    private InvitationDTO invitationDTO;

    public EditInvitationCase() {
        super("Edit Invitation", URLProperty.getURL("Invitations.url"));
        this.httpRequest = new HTTPRequest<>(InvitationDTO.class);
    }

    @Override
    public void getInput() {
        Application.IO.out("invitation id: ");//ha autogenerated lesz ez nem kell
        invitationDTO = httpRequest.get(getUrl() + Application.IO.getLong());
        Application.IO.outln(invitationDTO.toString());
        Application.IO.out("Description: ");
        invitationDTO.setDescription(Application.IO.getString());
        Application.IO.out("Event id: ");
        invitationDTO.setEventId(Application.IO.getLong());
        Application.IO.out("Invitation status" + Arrays.asList(InvitationStatus.values()) + ": ");
        invitationDTO.setStatus(getInvitationStatus());
    }

    @Override
    public void executeCase() {
        Application.IO.outln(httpRequest.put(getUrl(), invitationDTO).toString());
    }

}
